---
Name: authsmtp-module-config
After:
  - 'cms/*'
  - 'framework/*'
---
AuthSMTPService:
  host: mail.authsmtp.com
  port: 2525
  tls: true
  log_level: 3      # 3 = errors, 6 = info, 7 = debug
  queue: true
  send_window_size: 2
  allow_empty_body: true
#  add following 5 settings in your project config e.g. _config/authsmtp.yml
#  user: ''           # the user you login to AuthSMTP console with
#  password: ''       # the password you login to AuthSMTP console with
#  allowed_from: [''] # A list of the domains that emails may be sent from. This should be a valid domain sender in AuthSMTP config
#  from: ''           # who all emails will be sent from if the sender is not allowed as above and no SS_SEND_ALL_EMAILS_FROM is already set will set it. This should be a valid sender in AuthSMTP config
#  queue: true        # turn queuing on or off