---
Name: authsmtp-module-config
---
AuthSMTPConfig:
  host: mail.authsmtp.com
  port: 2525
  tls: true
  log_level: 3      # 3 = errors, 6 = info, 7 = debug
  queue: true
#  add following 3 settings in your project config e.g. _config/authsmtp.yml
#  user: ''         # the user you login to AuthSMTP console with
#  password: ''     # the password you login to AuthSMTP console with
#  from: ''         # who all emails will be sent from if no SS_SEND_ALL_EMAILS_FROM is already set will set it. This should be a valid sender in AuthSMTP config
#  queue: true      # turn queuing on or off